name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: lint, build, test and package
        run: |
          npm install -g pnpm @vscode/vsce
          pnpm install
          pnpm vscode:prepublish
          vsce package